spring.application.name=coauthor-analysis
# HikariCP 连接池配置
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=5
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:coauthoranalysis;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=2005102443997k7k

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
server.port=8080


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



# Web配置
server.servlet.context-path=/
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# 显示所有端点信息
management.endpoints.web.exposure.include=*
# 显示Spring数据初始化日志
logging.level.org.springframework.jdbc.datasource.init=DEBUG
